In [1]:
import numpy as np
import pandas as pd

In [7]:
a = np.array(np.arange(12, 24))
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

In [10]:
a.reshape(3,4)

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [11]:
a.reshape(6,2)

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [13]:
a.reshape(4,3)

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [14]:
a.reshape(2,6)

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [16]:
a.reshape(12,1)

array([[12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23]])

In [17]:
a.reshape(3,-1)

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [18]:
a.reshape(6,-1)

array([[12, 13],
       [14, 15],
       [16, 17],
       [18, 19],
       [20, 21],
       [22, 23]])

In [19]:
a.reshape(4,-1)

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [21]:
a.reshape(-1,6)

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [22]:
a.reshape(-1,1)

array([[12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23]])

In [30]:
x = np.random.randn(3, 4)
np.size(x)

12

In [31]:
x1 = x.reshape(1,12)
np.size(x1)

12

In [39]:
a = np.arange(20, 0, -2)
a

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

In [41]:
b = np.arange(20, 1, -2).reshape(1,10)
b

array([[20, 18, 16, 14, 12, 10,  8,  6,  4,  2]])

# a - одномерный массив, b - двумерный

In [44]:
a = np.zeros((2, 2))
b = np.ones((3, 2))
c = np.vstack((a, b))
np.size(c)

10

In [48]:
a = np.arange(0, 12, 1)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [52]:
A = a.reshape(4,3)
A

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [53]:
At = A.T
At

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [54]:
B = A.dot(At)
B

array([[  5,  14,  23,  32],
       [ 14,  50,  86, 122],
       [ 23,  86, 149, 212],
       [ 32, 122, 212, 302]])

B_inv = np.linalg.inv(B)
## отпределитель равен 0

In [57]:
np.random.seed(42)

In [59]:
c = np.random.randint(0, 16, (1,16))
c

array([[ 3, 12, 14, 10,  7, 12,  4,  6,  9,  2,  6, 10, 10,  7,  4,  3]])

In [62]:
C = c.reshape(4,4)
C

array([[ 3, 12, 14, 10],
       [ 7, 12,  4,  6],
       [ 9,  2,  6, 10],
       [10,  7,  4,  3]])

In [64]:
D = B + C*10
D

array([[ 35, 134, 163, 132],
       [ 84, 170, 126, 182],
       [113, 106, 209, 312],
       [132, 192, 252, 332]])

In [65]:
np.linalg.det(D)

21320000.000000034

In [66]:
np.linalg.matrix_rank(D)

4

In [75]:
D_inv = np.linalg.inv(D)
D_inv

array([[-0.0421257 , -0.04781989, -0.07423077,  0.11272233],
       [ 0.00713133,  0.01837899,  0.00807692, -0.02050094],
       [-0.00235084, -0.03018386, -0.02807692,  0.04386679],
       [ 0.01440901,  0.03129456,  0.04615385, -0.06324578]])

In [77]:
D_inv[D_inv > 0] = 1
D_inv[D_inv < 0] = 0
D_inv


array([[0., 0., 0., 1.],
       [1., 1., 1., 0.],
       [0., 0., 0., 1.],
       [1., 1., 1., 0.]])

In [80]:
E = np.where(D_inv, B, C)
E

array([[  3,  12,  14,  32],
       [ 14,  50,  86,   6],
       [  9,   2,   6, 212],
       [ 32, 122, 212,   3]])