In [1]:
import numpy as np

## Задание 1

In [7]:
a = np.array([[ 1, 2, 3, 3, 1], [6, 8, 11, 10, 7]], dtype = int).T
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [8]:
mean_a = a.mean(axis = 0)
mean_a

array([2. , 8.4])

### Задание 2

In [9]:
a_centered = a - mean_a
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

### Задание 3

In [17]:
a_centered_sp = a_centered[0:,0]@a_centered[0:,1]
a_centered_sp

8.0

In [21]:
a_centered_sp / (a_centered.shape[0] - 1)

2.0

### Задание 4

In [22]:
np.cov(a.T)

array([[1. , 2. ],
       [2. , 4.3]])